import {LinkedList} from "./linked-list"

const linkedList = new LinkedList<number>()
linkedList.addNode(1)
linkedList.addNode(2)
linkedList.addNode(3)
linkedList.addNode(4)
linkedList.addNode(5)

linkedList.showLinkedList()
linkedList.searchNode(3)
linkedList.deleteNode(3)
linkedList.showLinkedList()
linkedList.searchNode(3)
linkedList.showHeadNode()
linkedList.showTailNode()
linkedList.deleteNode(1)
linkedList.deleteNode(2)
linkedList.deleteNode(4)
linkedList.deleteNode(5)
linkedList.showLinkedList()
linkedList.showHeadNode()
linkedList.showTailNode()
linkedList.deleteNode(5)
linkedList.searchNode(5)
